<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="figma_meta_model" nsURI="www.figma_meta_model.com" nsPrefix="figma_meta_model">
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentPropertyDefinitionType">
    <eLiterals name="BOOLEAN"/>
    <eLiterals name="TEXT" value="1"/>
    <eLiterals name="VARIANT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutSizing">
    <eLiterals name="FIXED"/>
    <eLiterals name="HUG" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Alignment">
    <eLiterals name="MIN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="NODE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TriggerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COMPONENT_SET" eSuperTypes="#//Children">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemSpacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerRadius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerSmoothing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strokeDashes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentPropertyDefinitions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontFamily" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontPostScriptName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAutoResize" eType="#//TextAutoResize"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="letterSpacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineHeightPercent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineHeightPx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineHeightUnit" eType="#//LineHeightUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAlignHorizontal" eType="#//TextAlignment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAlignVertical" eType="#//TextAlignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowStartingPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StrokeType">
    <eLiterals name="SOLID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//Children">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overrides" upperBound="-1"
        eType="#//Override" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentProperties" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frame" eSuperTypes="#//Children">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutMode" eType="#//LayoutMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutWrap" eType="#//WrapType"
        defaultValueLiteral="NO_WRAP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutSizingHorizontal"
        eType="#//LayoutSizing" defaultValueLiteral="FIXED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutSizingVertical" eType="#//LayoutSizing"
        defaultValueLiteral="FIXED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutAlign" eType="#//LayoutAlign"
        defaultValueLiteral="INHERIT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterAxisSizingMode"
        eType="#//AxisSizingMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemSpacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryAxisSizingMode"
        eType="#//AxisSizingMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterAxisAlignItems"
        eType="#//AxisAlign"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryAxisAlignItems"
        eType="#//AxisAlign"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerRadius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerSmoothing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individualStrokeWeights"
        eType="#//StrokeWeight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutGrids" upperBound="-1"
        eType="#//LayoutGrid" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AxisSizingMode">
    <eLiterals name="FIXED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="c" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineHeightUnit">
    <eLiterals name="INTRINSIC_"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//Children"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutAlign">
    <eLiterals name="INHERIT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Horizontal">
    <eLiterals name="LEFT" literal="LEFT"/>
    <eLiterals name="RIGHT" literal="RIGHT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionType">
    <eLiterals name="PUSH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Vertical">
    <eLiterals name="BOTTOM"/>
    <eLiterals name="TOP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPropertyDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ComponentPropertyDefinitionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variantOptions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//Children">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutAlign" eType="#//LayoutAlign"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutGrow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutSizingHorizontal"
        eType="#//LayoutSizing" defaultValueLiteral="FIXED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutSizingVertical" eType="#//LayoutSizing"
        defaultValueLiteral="FIXED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//Style"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineTypes" upperBound="-1"
        eType="#//LineType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineIndentations" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maskType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paddingBottom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paddingLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paddingRight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paddingTop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryAxisAlignItems"
        eType="#//AxisAlign"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryAxisSizingMode"
        eType="#//AxisSizingMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionEasing" eType="#//EasingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionNodeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterAxisAlignItems"
        eType="#//AxisAlign"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterAxisSizingMode"
        eType="#//AxisSizingMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutMode" eType="#//LayoutMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemSpacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerRadius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerSmoothing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componenSets" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineType">
    <eLiterals name="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigmaApp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="figma"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//Document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSets" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Children">
    <eStructuralFeatures xsi:type="ecore:EReference" name="absoluteBoundingBox" lowerBound="1"
        eType="#//Dimensions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="absoluteRenderBounds" lowerBound="1"
        eType="#//Dimensions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DocumentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clipsContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" eType="#//Constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fills" eType="#//Background"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strokeAlign" eType="#//StrokeAlign"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strokeWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blemdMode" eType="#//BlendMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scrollBehavior" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srokes" upperBound="-1"
        eType="#//Srokes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Children" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//Background"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
        eType="#//Interaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentPropertyReferences"
        upperBound="-1" eType="#//ComponentPropertyReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scrollBehavior" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="SCROLLS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DocumentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" eType="#//Children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraints">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" eType="#//Horizontal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertical" eType="#//Vertical"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Easing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EasingType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BlendMode">
    <eLiterals name="NORMAL"/>
    <eLiterals name="PASS_THROUGH" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrototypeDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowStartingPoints" upperBound="-1"
        eType="#//FlowStartingPoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerType">
    <eLiterals name="ON_CLICK"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Override">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overriddenFields" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TextAutoResize">
    <eLiterals name="WIDTH_AND_HEIGHT"/>
    <eLiterals name="HEIGHT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Directions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TransitionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchLayers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="easing" eType="#//Easing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigation" eType="#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//Children">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StrokeAlign">
    <eLiterals name="CENTER"/>
    <eLiterals name="INSIDE"/>
    <eLiterals name="OUTSIDE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DocumentType">
    <eLiterals name="DOCUMENT"/>
    <eLiterals name="CANVAS" value="1"/>
    <eLiterals name="RECTANGLE" value="2"/>
    <eLiterals name="FRAME" value="3"/>
    <eLiterals name="TEXT" value="4"/>
    <eLiterals name="COMPONENT" value="5"/>
    <eLiterals name="COMPONENT_SET" value="6" literal="COMPONENT_SET"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Srokes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blendMode" eType="#//BlendMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//StrokeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TextAlignment">
    <eLiterals name="CENTER"/>
    <eLiterals name="LEFT" value="1"/>
    <eLiterals name="TOP" value="2"/>
    <eLiterals name="RIGHT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScrollBehavior">
    <eLiterals name="SCROLLS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigmaNodeApp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thumbnailUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="figma"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//Nodes" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Navigation">
    <eLiterals name="NAVIGATE"/>
    <eLiterals name="SCROLL_TO" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EffectType">
    <eLiterals name="BACKGROUND_BLUR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StrokeWeight">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AxisAlign">
    <eLiterals name="CENTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Directions">
    <eLiterals name="LEFT"/>
    <eLiterals name="RIGHT" value="1"/>
    <eLiterals name="BOTTOM" value="2"/>
    <eLiterals name="TOP" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EasingType">
    <eLiterals name="EASE_OUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Canvas" eSuperTypes="#//Children">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prototypeStartNodeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prototypeDevice" eType="#//PrototypeDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blenMode" eType="#//BlendMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EffectType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutMode">
    <eLiterals name="HORIZONTAL"/>
    <eLiterals name="VERTICAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WrapType">
    <eLiterals name="NO_WRAP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGrid">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//Alignment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gutterSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimensions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BackgroundType">
    <eLiterals name="SOLID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Background">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blendMode" eType="#//BlendMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" lowerBound="1" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentSetId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentationLinks" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VECTOR" eSuperTypes="#//Children"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nodes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//NodeItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPropertyReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//ComponentPropertyReferenceKeyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentPropertyReferenceKeyType">
    <eLiterals name="characters"/>
    <eLiterals name="visible" value="1"/>
  </eClassifiers>
</ecore:EPackage>
